### IV and WOE

In [2]:
import pandas as pd
df = pd.read_excel('IV-WOE.xlsx')

import MyUtils
from MyUtils import IVandWOE

df,IV = IVandWOE(df)
print(IV)
df

IV =
0.1093

,Age Group,Total Number of Loans,Number of Bad Loans,Number of Good Loans,Distribution_Bad,Distribution_Good,WOE,IV
0,21 - 30,4821,206,4615,0.1353,0.0779,-0.5530,0.0318
1,30 - 36,10266,357,9909,0.2346,0.1672,-0.3388,0.0228
2,36 - 48,32926,776,32150,0.5099,0.5424,0.0618,0.0020
3,48 - 60,12788,183,12605,0.1202,0.2126,0.5701,0.0527
4,Total,60801,1522,59279,1.0000,1.0000,0.0000,0.0000

### Population Stability Index (PSI)

In [3]:
from MyUtils import PSI

xls = pd.ExcelFile('PSI,KS.xlsx')
df1 = pd.read_excel(xls, 'PSI')
df2 = pd.read_excel(xls, 'Expected%')
df2 = df2*100

df, PSI = PSI(df1, df2)
print(PSI)
df

PSI =
59.64996777661186

,Band Frequency,Actual_Percentage,Expected_Percentage,AcExDiff,lnAcEx,Index
<250,90,9.0,8.0,1.0,0.117783,0.117783
251–290,86,8.6,9.0,-0.4,-0.045462,0.018185
291–320,71,7.1,10.0,-2.9,-0.342490,0.993222
321–350,53,5.3,13.0,-7.7,-0.897243,6.908768
351–380,60,6.0,12.0,-6.0,-0.693147,4.158883
381–410,66,6.6,11.0,-4.4,-0.510826,2.247633
411–440,61,6.1,10.0,-3.9,-0.494296,1.927756
441–470,50,5.0,9.0,-4.0,-0.587787,2.351147
471–520,110,11.0,9.0,2.0,0.200671,0.401341
520<,353,35.3,8.0,27.3,1.484441,40.525251

### Kolmogorov-Smirnov (KS) Statistics

In [5]:
from MyUtils import KS

xls = pd.ExcelFile('PSI,KS.xlsx')
df = pd.read_excel(xls,"KS")
df = df.iloc[:,:3]

df, KS_value = KS(df)
print(KS_value)
df

KS =
57.77777777777778

,Decile,Non-Event,Event,Non_Event_Percent,Event_Percent,Cum_Per_Event,Cum_Per_Non_Event,KS
0,1,51,49,5.666667,49.0,49.0,5.666667,43.333333
1,2,81,19,9.000000,19.0,68.0,14.666667,53.333333
2,3,86,14,9.555556,14.0,82.0,24.222222,57.777778
3,4,90,10,10.000000,10.0,92.0,34.222222,57.777778
4,5,95,5,10.555556,5.0,97.0,44.777778,52.222222
5,6,99,1,11.000000,1.0,98.0,55.777778,42.222222
6,7,99,1,11.000000,1.0,99.0,66.777778,32.222222
7,8,99,1,11.000000,1.0,100.0,77.777778,22.222222
8,9,100,0,11.111111,0.0,100.0,88.888889,11.111111
9,10,100,0,11.111111,0.0,100.0,100.000000,0.000000
10,Total,900,100,100.000000,100.0,200.0,200.000000,0.000000